services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    networks:
      - inception
    env_file:
      - .env
networks:
  inception:
    driver: bridge
