services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - INCEPTION
  
  mariadb:
    build: ./requirements/mariadb
    networks:
      - INCEPTION

networks:
  INCEPTION:
    driver:
      bridge


