services:

  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
      - INCEPTION
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    ports:
      - 3306
    networks:
      - INCEPTION
    restart: always


  wordpress:
    build: ./requirements/wordpress
    ports:
      - 9000
    networks:
      - INCEPTION
    restart: always
    volumes:
      - wordpress_data:/var/www/html

networks:
  INCEPTION:
    driver:
      bridge

volumes:
  wordpress_data:



